name: Fast-DDS continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'

jobs:
  Running-CI:
    uses: ./.github/workflows/reusable-github-ci.yml
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    with:
      label: "Running-CI"
      os: "[\"windows-2019\",\"windows-2022\"]"
      config: "[\"RelWithDebInfo\"]"
      vs_toolset: "[\"v142\"]"
      colcon_args: "--metas ignore.meta"
      cmake_args: "-DCMAKE_FIND_DEBUG_MODE=OFF"
